---
version: 2.0
builds:
  build-gpu-operator:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               IMAGE_NAME=amd-gpu-operator PROJECT_VERSION=v1.4.0 HOURLY_TAG_LABEL=$RELEASE IMAGE_TAG=latest make docker-build && \
               IMAGE_NAME=amd-gpu-operator PROJECT_VERSION=v1.4.0 HOURLY_TAG_LABEL=$RELEASE IMAGE_TAG=latest make docker-save && \
               IMAGE_NAME=amd-gpu-operator PROJECT_VERSION=v1.4.0 HOURLY_TAG_LABEL=$RELEASE IMAGE_TAG=latest make docker-build-utils && \
               IMAGE_NAME=amd-gpu-operator PROJECT_VERSION=v1.4.0 HOURLY_TAG_LABEL=$RELEASE IMAGE_TAG=latest make docker-save-utils && \
               IMAGE_NAME=amd-gpu-operator PROJECT_VERSION=v1.4.0 IMAGE_TAG=$PROJECT_VERSION make bundle-build && \
               IMAGE_NAME=amd-gpu-operator PROJECT_VERSION=v1.4.0 IMAGE_TAG=$PROJECT_VERSION make bundle-save && \
               mv amd-gpu-operator-olm-bundle.tar.gz internal-gpu-operator-olm-bundle.tar.gz && \
               DOCKER_REGISTRY=amdpsdo IMAGE_NAME=gpu-operator PROJECT_VERSION=v1.4.0 HOURLY_TAG_LABEL=$RELEASE IMAGE_TAG=$RELEASE make bundle-build && \
               DOCKER_REGISTRY=amdpsdo IMAGE_NAME=gpu-operator PROJECT_VERSION=v1.4.0 HOURLY_TAG_LABEL=$RELEASE IMAGE_TAG=$RELEASE make bundle-save && \
               mv gpu-operator-olm-bundle.tar.gz amdpsdo-gpu-operator-olm-bundle.tar.gz"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/amd-gpu-operator-latest.tar.gz
     - /gpu-operator/amd-gpu-operator-utils-latest.tar.gz
     - /gpu-operator/internal-gpu-operator-olm-bundle.tar.gz
     - /gpu-operator/amdpsdo-gpu-operator-olm-bundle.tar.gz
    repo-dependencies:
      /ws/builder/kernel-module-management:
        repository: https://github.com/pensando/kernel-module-management
        reference: 3c4df0af409cecd65e006e63908611703fb03748

  build-gpu-operator-k8s:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               mkdir -p build/charts && \
               PROJECT_VERSION=v1.4.0 IMAGE_TAG=$PROJECT_VERSION KMM_IMAGE_TAG=$PROJECT_VERSION make helm && \
               cp helm-charts-k8s/gpu-operator-helm-k8s-v1.4.0.tgz \
                  build/charts/internal-gpu-operator-helm-k8s-v1.4.0.tgz && \
               DOCKER_REGISTRY=docker.io/amdpsdo IMAGE_NAME=gpu-operator PROJECT_VERSION=v1.4.0 IMAGE_TAG=${RELEASE:-latest} KMM_IMAGE_TAG=$PROJECT_VERSION make helm && \
               cp helm-charts-k8s/gpu-operator-helm-k8s-v1.4.0.tgz \
                  build/charts/amdpsdo-gpu-operator-helm-k8s-v1.4.0.tgz"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/build/charts/internal-gpu-operator-helm-k8s-v1.4.0.tgz
     - /gpu-operator/build/charts/amdpsdo-gpu-operator-helm-k8s-v1.4.0.tgz
    repo-dependencies:
      /ws/builder/kernel-module-management:
        repository: https://github.com/pensando/kernel-module-management
        reference: 3c4df0af409cecd65e006e63908611703fb03748

  build-external-device-metrics-exporter:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter \
       --alien-repo pensando/device-metrics-exporter --alien-target build-device-metrics-exporter-docker-ubi9.6 --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/docker/device-metrics-exporter-latest.tar.gz
     - /device-metrics-exporter/docker/device-metrics-exporter-latest.metadata

  build-external-test-runner:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter && \
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-test-runner \
       --alien-repo pensando/device-metrics-exporter --alien-target build-test-runner-docker --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/docker/testrunner/test-runner-latest.tar.gz
     - /device-metrics-exporter/docker/testrunner/test-runner-latest.metadata

  build-external-test-runner-agfhc:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter && \
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-test-runner-agfhc \
       --alien-repo pensando/device-metrics-exporter --alien-target build-test-runner-docker-agfhc --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/docker/testrunner/test-runner-latest-agfhc.tar.gz
     - /device-metrics-exporter/docker/testrunner/test-runner-latest-agfhc.metadata

  build-external-config-manager:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-config-manager && \
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-config-manager \
       --alien-repo pensando/device-config-manager --alien-target build-device-config-manager-docker-ubi9 --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
      - /device-config-manager/docker/obj/device-config-manager.tgz
      - /device-config-manager/docker/obj/device-config-manager.metadata

  build-external-kernel-module-manager:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /kernel-module-management && \
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-kernel-module-manager \
       --alien-repo pensando/kernel-module-management --alien-target build-kernel-module-management --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /kernel-module-management/kernel-module-management-operator.tar.gz
     - /kernel-module-management/kernel-module-management-operator.metadata

  build-external-kernel-module-signimage:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /kernel-module-management && \
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-kernel-module-signimage \
       --alien-repo pensando/kernel-module-management --alien-target build-signer --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /kernel-module-management/kernel-module-management-signimage.tar.gz
     - /kernel-module-management/kernel-module-management-signimage.metadata

  build-external-kernel-module-webhook-server:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /kernel-module-management && \
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-kernel-module-webhook-server \
       --alien-repo pensando/kernel-module-management --alien-target build-webhook-server --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /kernel-module-management/kernel-module-management-webhook-server.tar.gz
     - /kernel-module-management/kernel-module-management-webhook-server.metadata

  build-external-kernel-module-worker:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /kernel-module-management && \
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-kernel-module-worker \
       --alien-repo pensando/kernel-module-management --alien-target build-worker --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /kernel-module-management/kernel-module-management-worker.tar.gz
     - /kernel-module-management/kernel-module-management-worker.metadata

  build-external-device-metrics-exporter-helm-artifact:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter/helm-charts &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter-helm-artifact \
       --alien-repo pensando/device-metrics-exporter --alien-target build-helm-artifact --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/helm-charts/device-metrics-exporter-charts.tgz
     - /device-metrics-exporter/helm-charts/device-metrics-exporter-charts.metadata
     - /device-metrics-exporter/tools/techsupport_dump.sh

  build-external-device-metrics-exporter-debian-package-ub22.04:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter/bin &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter-debian-package-ub22.04 \
       --alien-repo pensando/device-metrics-exporter --alien-target build-debian-package-ub22.04 --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/bin/amdgpu-exporter_22.04_amd64.deb
     - /device-metrics-exporter/bin/amdgpu-exporter_22.04_amd64.metadata

  build-external-device-metrics-exporter-debian-package-ub24.04:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter/bin &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter-debian-package-ub24.04 \
       --alien-repo pensando/device-metrics-exporter --alien-target build-debian-package-ub24.04 --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/bin/amdgpu-exporter_24.04_amd64.deb
     - /device-metrics-exporter/bin/amdgpu-exporter_24.04_amd64.metadata

  gpu-operator-olm-bundle-sanity-build:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter/bin &&
       /gpu-operator/ci-internal/flexibuilder/build.sh gpu-operator-olm-bundle-sanity-build \
       --alien-repo pensando/gpu-operator --alien-target build-gpu-operator --alien-branch ${JOB_BASE_BRANCH}"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /gpu-operator/artifacts.metadata
     - /gpu-operator/amdpsdo-gpu-operator-olm-bundle.tar.gz

  # Following are added for specific v1.4.2 DME release
  build-external-device-metrics-exporter-v1.4.2:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter \
       --alien-repo pensando/device-metrics-exporter --alien-target build-device-metrics-exporter-docker-ubi9.6 --alien-branch v1.4.2"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/docker/device-metrics-exporter-latest.tar.gz

  build-external-device-metrics-exporter-helm-artifact-v1.4.2:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter/helm-charts &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter-helm-artifact \
       --alien-repo pensando/device-metrics-exporter --alien-target build-helm-artifact --alien-branch v1.4.2"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/helm-charts/device-metrics-exporter-charts.tgz
     - /device-metrics-exporter/tools/techsupport_dump.sh

  build-external-device-metrics-exporter-debian-package-ub22.04-v1.4.2:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter/bin &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter-debian-package-ub22.04 \
       --alien-repo pensando/device-metrics-exporter --alien-target build-debian-package-ub22.04 --alien-branch v1.4.2"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/bin/amdgpu-exporter_22.04_amd64.deb

  build-external-device-metrics-exporter-debian-package-ub24.04-v1.4.2:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter/bin &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter-debian-package-ub24.04 \
       --alien-repo pensando/device-metrics-exporter --alien-target build-debian-package-ub24.04 --alien-branch v1.4.2"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/bin/amdgpu-exporter_24.04_amd64.deb

  # Following are added for specific v1.4.0.x DME patch-release
  build-external-device-metrics-exporter-v1.4.0:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter \
       --alien-repo pensando/device-metrics-exporter --alien-target build-device-metrics-exporter-docker-ubi9.6 --alien-branch v1.4.0"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/docker/device-metrics-exporter-latest.tar.gz

  build-external-device-metrics-exporter-helm-artifact-v1.4.0:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter/helm-charts &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter-helm-artifact \
       --alien-repo pensando/device-metrics-exporter --alien-target build-helm-artifact --alien-branch v1.4.0"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/helm-charts/device-metrics-exporter-charts.tgz
     - /device-metrics-exporter/tools/techsupport_dump.sh

  build-external-device-metrics-exporter-debian-package-ub22.04-v1.4.0:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter/bin &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter-debian-package-ub22.04 \
       --alien-repo pensando/device-metrics-exporter --alien-target build-debian-package-ub22.04 --alien-branch v1.4.0"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/bin/amdgpu-exporter_22.04_amd64.deb

  build-external-device-metrics-exporter-debian-package-ub24.04-v1.4.0:
    commands: ["sh", "-c", "export CI_USE_SANITY_BUILD=1 && mkdir -p /device-metrics-exporter/bin &&
       /gpu-operator/ci-internal/flexibuilder/build.sh build-external-device-metrics-exporter-debian-package-ub24.04 \
       --alien-repo pensando/device-metrics-exporter --alien-target build-debian-package-ub24.04 --alien-branch v1.4.0"]
    owners: ["email:srivatsa.sangli@amd.com"]
    artifacts:
     - /device-metrics-exporter/bin/amdgpu-exporter_24.04_amd64.deb

targets:
  gpu-operator-sanity:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make generate && make vet && make lint && make unit-test"]
    owners: ["email:mharkara@amd.com"]
    area:
    sub-area:
  copyright-checks:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make copyrights"]
    owners: ["email:sajmera@amd.com"]
    area:
    sub-area:
    feature:
  docs-sanity:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make docs"]
    owners: ["email:yan.sun3@amd.com"]
    area:
    sub-area:
    feature:
  docs-lint:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make docs-lint"]
    owners: ["email:udayb@amd.com"]
    area:
    sub-area:
    feature:
  operator-e2e-sim:
    commands: ["sh", "-cx",
    "cd ci-internal && ./setup_e2e.sh;
    cd ../ && SIM_ENABLE=1 make all && SIM_ENABLE=1 make docker-push && helm repo add jetstack https://charts.jetstack.io --force-update && helm install cert-manager jetstack/cert-manager --namespace cert-manager  --create-namespace --version v1.15.1 --set crds.enabled=true && SIM_ENABLE=1 SKIP_INSTALL_DEFAULT_CR=1 make helm-install && sleep 60 && kubectl get pods -A | grep amd && cd ci-internal && ./create_secret.sh && cd ../ && sleep 60 && kubectl get pods -A | grep amd && ci-internal/run_e2e.sh || E2E_FAILED=1; kubectl get pods -A | grep amd && SIM_ENABLE=1 SKIP_INSTALL_DEFAULT_CR=1 make helm-uninstall && make helm-e2e; [ -z \"$E2E_FAILED\" ]"]
    owners: ["email:sajmera@amd.com"]
    queue_name: ubuntu2204
    area:
    sub-area:
    feature:
    repo-dependencies:
      /ws/builder/kernel-module-management:
        repository: https://github.com/pensando/kernel-module-management
        reference: 3c4df0af409cecd65e006e63908611703fb03748
image:
  bind_dir: "/gpu-operator"
  work_dir: "/gpu-operator"

logfiles:
  - /gpu-operator/techsupport.tgz
  - /gpu-operator/e2e-artifacts.tgz

jobs:
  api:
    labels: ["CI-Precheckin-Gpuoperator"]
  asset-build:
    labels: ["CI-Sanity-Build"]
  tests/jobs/sanity:
    labels: ["CI-Pytest-Sanity"]
  tests/jobs/regression:
    labels: ["CI-Sanity-Build", "CI-Pytest-Regression"]
  tests/jobs/operand-release/v1.4.2:
    labels: ["CI-Pytest-Operand-Release-v1.4.2"]
  tests/jobs/operand-release/v1.4.0.x:
    labels: ["CI-Pytest-Operand-Release-v1.4.0"]
      # ci-internal:
    #    labels: [""]
host_mounts:
  "/sys/module": "/sys/module"
  "/lib/modules": "/lib/modules"
